<?php

return [
    'default' => [
        // length of captcha string
        'length'        => 4,

        // width of image
        'width'         => 120,

        // height of image
        'height'        => 36,

        // quality of png image generated by captcha service
        'quality'       => 10,

        // number of image lines
        'lines'         => 4,

        // contrast of image, value from 0 - 100
        'contrast'      => 50,

        // available characters for generate captcha text
        'characters'    =>  '0123456789',
    ],
];
